#!/usr/bin/env node
/**
 * bridge:generate-types
 *
 * Generates a typed client file from a Service Worker background script that
 * uses `createBridge(router)`.
 *
 * Usage:
 *   npx tsx scripts/generate-types.ts --input ./src/background.ts --output ./src/bridge-client.d.ts
 *
 * The generated file exports a `BridgeClient` type alias:
 *   import type { InferClient } from 'extension-bridge'
 *   import type { <router> } from '<relative-path-to-input>'
 *   export type BridgeClient = InferClient<typeof <router>>
 *
 * Requirements:
 *   - The background script must export the router variable used in createBridge()
 *   - Example:  export const router = { ... };  createBridge(router).listen()
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

// ─── CLI args ─────────────────────────────────────────────────────────────────

function getArg(flag: string): string | undefined {
  const idx = process.argv.indexOf(flag);
  return idx !== -1 ? process.argv[idx + 1] : undefined;
}

const inputArg = getArg('--input');
const outputArg = getArg('--output');

if (!inputArg || !outputArg) {
  console.error('Usage: generate-types --input <background.ts> --output <bridge-client.d.ts>');
  process.exit(1);
}

const inputPath = path.resolve(inputArg);
const outputPath = path.resolve(outputArg);

// ─── Parse input file ─────────────────────────────────────────────────────────

if (!fs.existsSync(inputPath)) {
  console.error(`Input file not found: ${inputPath}`);
  process.exit(1);
}

const source = fs.readFileSync(inputPath, 'utf-8');

// Find: createBridge(routerVariableName, ...)
const bridgeCallMatch = source.match(/createBridge\s*\(\s*(\w+)/);
if (!bridgeCallMatch) {
  console.error(
    `Could not find createBridge() call in ${inputPath}.\n`
    + `Make sure the file contains: createBridge(router, options?)`,
  );
  process.exit(1);
}

const routerName = bridgeCallMatch[1]!;

// Verify the router variable is exported
const exportPattern = new RegExp(
  `export\\s+(?:const|let|var|type|interface)\\s+${routerName}\\b`,
);
if (!exportPattern.test(source)) {
  console.error(
    `Router variable '${routerName}' is not exported from ${inputPath}.\n`
    + `Add 'export' before the variable declaration, e.g.:\n`
    + `  export const ${routerName} = { ... }`,
  );
  process.exit(1);
}

// ─── Compute relative import path ─────────────────────────────────────────────

// Relative path from the output file's directory to the input file (without extension)
const outputDir = path.dirname(outputPath);
let relativePath = path.relative(outputDir, inputPath).replace(/\.tsx?$/, '');

// Ensure the path starts with ./ or ../
if (!relativePath.startsWith('.')) {
  relativePath = `./${relativePath}`;
}

// ─── Generate output ──────────────────────────────────────────────────────────

const generatedAt = new Date().toISOString();
const inputRelative = path.relative(process.cwd(), inputPath);
const outputRelative = path.relative(process.cwd(), outputPath);

const content = `// Auto-generated by bridge:generate-types
// Source: ${inputRelative}
// Generated: ${generatedAt}
// Do NOT edit manually — run \`bridge:generate-types\` to regenerate.

import type { InferClient } from 'extension-bridge';
import type { ${routerName} } from '${relativePath}';

export type BridgeClient = InferClient<typeof ${routerName}>;
`;

// Ensure output directory exists
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, content, 'utf-8');

console.log(`✅ Generated: ${outputRelative}`);
console.log(`   Router: ${routerName} (from ${inputRelative})`);
console.log(`   Usage:\n     import type { BridgeClient } from '${outputRelative.replace(/\.d\.ts$/, '')}'`);
